#!/usr/bin/env python3.4

from sys import path
path.append('lib')  #add lib folder to module search path
from argparse import ArgumentParser
import logging

if __name__ == "__main__":
    parser = ArgumentParser(description='pyships: play Battleships via LAN')
    parser.add_argument(
        '-s', '--server', action='store_true',
        help='start a pyships server'
    )
    args = parser.parse_args()

    #TODO set logging level via args
    logging.basicConfig(level=logging.INFO, format="%(levelname)s:%(filename)s:%(funcName)s:%(message)s")

    if args.server:
        #from Server import Server or something
        print("Server not implemented yet!")
    else:
        from client import Game
        Game.run()
