#!/usr/bin/env python3.4

from sys import path
path.append('lib')  #add lib folder to module search path
from argparse import ArgumentParser


if __name__ == "__main__":
    parser = ArgumentParser(description='pyships: play Battleships via LAN.')
    parser.add_argument(
        '-s', '--server', action='store_true',
        help='start a pyships server instead of a client'
    )
    args = parser.parse_args()

    if args.server:
        #from Server import Launcher
        print("Server not implemented yet!")
    else:
        from client import Game
        Game.run()